# config file for file-synching into other repos
pp-mo/test_sync_target:
  - source: .github/workflows/template_files/sample_file_1.txt
    dest: ./synched_files/sample_file_1.txt
  - source: .github/workflows/template_files/sample_file_2.txt
    dest: ./synched_files/sample_file_2.txt
