name: Fetch 3rd-party versions
on: workflow_dispatch
jobs:
  fetch3rdparty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Update templates from master location
        run: |
          wget https://github.com/pp-mo/test_sync_3rdparty/raw/main/master_template1.txt -O ./master_templates/sample_file_1.txt
      - name: Create update PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SYNCTEST_PAT }}
          git-token: ${{ secrets.SYNCTEST_PAT }}
          branch: staged_master_updates
          commit-message: Template updates from master locations

